#############################
# Config Parse Test Program #
#                           #
# Bryant Moscon - 2013      #
#############################

test: test.cc ../src/config_parse.cc ../src/config_parse.hpp
	g++ -ggdb3 -std=c++11 -o test -I../src/ test.cc ../src/config_parse.cc

clean:
	rm test